### ISSUE TITLE
Common stanzas are not understood

### ISSUE THREAD

**Issue by jchia** [Avi-D-coder/implicit-hie#1]
What about using Cabal to do the parsing?

**Comment by Avi-D-coder** [comment]
We can't depend on cabal because it's a very large dependency and hie-bios can't depend on cabal.

 There are a few moreknown bugs having to due with generating cabal hie.yamls, try again tomorrow if you're having issues.

Cabal-fmt implemented a full cabal parser if ours gets to complex I look in to using theirs

**Comment by Avi-D-coder** [comment]
Can you post the cabal file that fails?

**Comment by jchia** [comment]
Nothing complicated or surprising. The hs-source-dirs is not picked up from the common stanza.

```
cabal-version: 2.2

name:           test
version:        0.1.0.0
description:    test
category:       test
build-type:     Simple

common common
  default-language: Haskell2010
  hs-source-dirs: app

executable test
  import: common
  main-is: test.hs
  build-depends:
      base

```

**Comment by Avi-D-coder** [comment]
Thanks. This is not currently a priority, ~but I will get to it eventually~

**Comment by refaelsh** [comment]
+1

**Comment by fendor** [comment]
Should be fixed by #48

**Comment by Avi-D-coder** [comment]
@fendor I don't think it's fixed.
I tested it locally, and it did not work.
